class Action:
    Right = '>'
    Left = '<'
    Up = '^'
    Down = 'v'
    Random = '?'  # !
    Right_if = '_'  # else left
    Down_if = '|'  # else up
    Add = '+'
    Sub = '-'
    Mul = '*'
    Div = '/'
    Module_div = '%'
    Log_not = '!'
    Greater_then = '`'  # Greater than: Pop a and b, then push 1 if b>a, otherwise zero.
    String_mode = '\"'
    Duplicate = ':'
    Swap = '\\'
    Discard = '$'
    Print_int = '.'
    Print_char = ','
    Skip_next = '#'
    Ask_number = '&'
    Ask_char = '~'
    Nothing = ' '
    Exit = '@'
    Put = 'p'
    Get = 'g'
    Jump = 'j'
